'''this file is how I generated figures to compare the wave height as a
function of distance for different cases. It loads .csv files and finds the 
midline heights of the datasets. .csv files are used because SWAN is
computationally expensive. It is more straightforward to generate good figures
to work with saved datasets rather than conducting 9 consecutive Capytaine
and SWAN runs. You will need to change the file path in line 39 to run.'''

import numpy as np
import matplotlib.pyplot as plt

# Constants
xgrid = 3000
ygrid = 5000
mxc = 300
myc = 500
x_conversion = xgrid / (mxc + 1)
y_conversion = ygrid / (myc + 1)
x_investigated = int(1550 / x_conversion)       # dead x-center of array
y_investigated = int(4482 / y_conversion)       # y = 0 m from array

# Load and reshape data
def load_and_reshape(file_path):
    data = np.loadtxt(file_path, delimiter=',')
    return data.reshape(mxc + 1, myc + 1)

file_paths = [
    'blank.csv',
    #'atten_1a.csv','atten_1b.csv','atten_1c.csv','atten_2a.csv','atten_3b.csv'
    #'break_1a.csv','break_1b.csv','break_1c.csv','break_2a.csv','break_3b.csv' 
    #'OS_1a.csv','OS_1b.csv','OS_1c.csv','OS_2a.csv','OS_3b.csv' 
    #'PA_1a.csv','PA_1b.csv','PA_1c.csv','PA_2a.csv','PA_3b.csv'
    #'atten_1d.csv',
    #'break_1d.csv',
    #'OS_1d.csv',
    #'PA_1d.csv'
    'irregular_test.csv'
]

# you will need to change the file path to run
#data_arrays = [load_and_reshape(f'/mnt/c/Users/ov162/transmission-reflection/data/{fp}') for fp in file_paths]
### FOR TEST ONLY ####
data_arrays = [load_and_reshape(f'/mnt/c/Users/ov162/transmission-reflection/run_all/data/{fp}') for fp in file_paths]
# Extract midline heights
midline_heights = [data[:y_investigated, x_investigated] for data in data_arrays]

# Calculate percent decrease
midline_height_blank = midline_heights[0]
percent_decrease = 100 * (midline_height_blank - np.array(midline_heights[1:])) / midline_height_blank

# Calculate distance from array
distance_from_array = abs(np.linspace(0, y_investigated * y_conversion, len(midline_heights[1])))# - ygrid)
#print(distance_from_array)
# Find the indices for the specified x-distances
x_distance_1nm = 5000 - 1852
x_distance_half_nm = 5000-(1852*2)
x_index_1nm = np.argmin(np.abs(distance_from_array - x_distance_1nm))
x_index_half_nm = np.argmin(np.abs(distance_from_array - x_distance_half_nm))

# Extract values at the specified x-distances for each file
percent_decrease_1nm_values = percent_decrease[:, x_index_1nm]
percent_decrease_half_nm_values = percent_decrease[:, x_index_half_nm]

# Print the extracted values for each file
for i, file_path in enumerate(file_paths[1:]):  # Skipping the blank file
    print(f"{file_path} - Percent decrease at 1852 meters: {percent_decrease_1nm_values[i]:.2f}%")
    #print(f"{file_path} - Percent decrease at 926 meters: {percent_decrease_half_nm_values[i]:.2f}%")


# Define color-blind friendly colors
cud_colors = ['#E69F00', '#56B4E9', '#009E73', '#0072B2', '#D55E00', '#CC79A7', '#000000', '#8B4513']

# Plot function
def plot_data(x, y_data, ylabel, filename):
    plt.figure()
    for y, label, color, linestyle in zip(y_data, plot_labels, cud_colors, ['-', '--', '-.', ':','-','--','-.',':']):
        plt.plot(x, y, label=label, color=color, linestyle=linestyle)
    #plt.axvline(x=1852, color='black', linestyle=':', label='1 nm')
    #plt.axvline(x=(1852)/2, color='black', linestyle='-')
    plt.xlabel('Distance from Array [m]')
    plt.ylabel(ylabel)
    plt.legend()
    plt.savefig(f'/mnt/c/Users/ov162/transmission-reflection/run_all/post_pro/{filename}.pdf')
    #plt.show()

# Plot wave heights
plot_labels = ['Attenuator', 'Breakwater', 'OSWEC','PA']
#plot_data(distance_from_array, midline_heights[1:], 'Wave Height [m]', 'compare_bodies')

# Plot percent decrease
plot_data(distance_from_array, percent_decrease, 'Decrease in Wave Height [%]', '1d_percent_decrease')

#def postpro(sfgrid_dat,xgrid,ygrid,mxc,myc,x,ya,yb):
import matplotlib.pyplot as plt
from matplotlib import ticker
import pandas as pd
import numpy as np


# this is where you define your body positions, I add approx half the
# set diameter so the markers are centered
x = [1490,1550,1610] 
ya, yb = 4500, 4450

wecx = [i + 10 for i in x]
wecy = [None] * len(wecx)
for i in range(len(wecx)):
    if i > 2:
        wecy[i] = yb
    else:
        wecy[i] = ya

# this command reads the output table generated by SWAN
#h_s = pd.read_table(sfgrid_dat, sep="\s+", header=None)


# this will load your data if you saved it previously and do not want to run SWAN again
h_s_irr = np.loadtxt('/mnt/c/Users/ov162/transmission-reflection/run_all/data/irregular_test.csv',delimiter=',')
h_s_blank = np.loadtxt('/mnt/c/Users/ov162/transmission-reflection/run_all/data/blank.csv',delimiter=',')
h_s = 100 * (h_s_blank - h_s_irr)/h_s_blank
true_mid_perc_dif = h_s[:y_investigated, x_investigated]
#print(true_mid_perc_dif)
plt.plot(distance_from_array,true_mid_perc_dif)
plt.show()

# this is defining your plotting parameters
nx, ny = (mxc + 1, myc + 1)
x = np.linspace(0, xgrid, nx)
y = np.linspace(0, ygrid, ny)
X, Y = np.meshgrid(x,y)

# now you are plotting
fig,ax = plt.subplots(1,1)
cp = ax.contourf(X,Y,h_s,40)
plt.scatter(wecx,wecy,marker='_',color='red',s=25, linewidth=2)
ax.set_xlabel('x [m]',fontsize=17)
ax.set_ylabel('y [m]',fontsize=17)
ax.ticklabel_format(axis='both',style='sci')
cbar = fig.colorbar(cp)
cbar.set_label('Wave Height',fontsize=17,rotation=270,labelpad=17)
cbar.ax.tick_params(labelsize=15)
#cp.set_clim(0.684, 0.81)                    # set to compare plots apples to apples
plt.xticks(fontsize=14, rotation=90)
plt.yticks(fontsize=14, rotation=90)
plt.tight_layout()
print('yip')
plt.savefig('perc_diff.pdf')
print('ee')
#plt.show()
