import sys
import os
import numpy as np
import pandas as pd
# Get the current directory of the script
current_dir = os.path.dirname(os.path.abspath(__file__))
parent_dir = os.path.dirname(current_dir)
hydro_dir = os.path.join(parent_dir, 'hydro')
swan_dir = os.path.join(parent_dir, 'swan')
sys.path.append(hydro_dir)
sys.path.append(swan_dir)
import run_coeffs
import run_swan

KR = [0.31557224629614655,0.31557224629614655,0.31557224629614655,0.31557224629614655,0.31557224629614655,0.31557224629614655]
KT = [0.6406240452795219,0.6406240452795219,0.6406240452795219,0.6406240452795219,0.6406240452795219,0.6406240452795219]
d = 18
x = [1490,1550,1610] 
ya, yb = 4500, 4450
H = 0.8
T = 5
xgrid = 3000
ygrid = 5000
mxc = int(xgrid/10)
myc = int(ygrid/10)
attenuator = False
# running a three body regular array case with kt and kr found with body modeled in isolation in BEM
six = False
swan_stag = False
sfgrid_dat, sfgrid_tbl = run_swan.generate_swan_input(KR, KT, d, x, ya, yb, H, T, xgrid, ygrid, mxc, myc,attenuator,six,swan_stag)

def save_wave_height_to_csv(sfgrid_dat, output_filename):
    # Determine the directory of the current script and the data folder path
    script_dir = os.path.dirname(__file__)
    data_folder = os.path.join(script_dir, 'data')
    
    # Ensure the data folder exists
    os.makedirs(data_folder, exist_ok=True)
    
    # Construct the full output file path
    output_csv_path = os.path.join(data_folder, output_filename)
    
    # Read the output table generated by SWAN
    h_s = pd.read_table(sfgrid_dat, sep="\s+", header=None)
    
    # Save the data to the CSV file
    np.savetxt(output_csv_path, h_s, delimiter=',')
    
    return h_s

h_s = save_wave_height_to_csv(sfgrid_dat, 'irregular_test.csv')