'''this file solves the hydrodynamics in hydro() and the wave elevation
in elevation(). hydro() will also use Capytaine's built in RAO solver if
controls=False. elevation() will compute the elevation due to incident 
waves, diffracted waves, and radiated waves, as well as multiply the
radiated waves generated by each body by the body's RAO and sum the 
radiated wave fields of every body before adding them to the incident
and diffracted. The math is detailed in the paper.'''

'''LAST UPDATE" OCT 16TH 2025'''

def hydro(array,B,depth,w,char_dim,controls,point_absorber):
    import capytaine as cpt
    import numpy as np
    import PTO

    g = 9.81                # gravitational constant (m/s^2)
    k = w**2/g              # wave number infinite depth (rad^2/m)
    lam = int(2*np.pi/k)    # wavelength infinite depth (m)
    
    # solving hydrodynamics using Capytaine solver
    solver = cpt.BEMSolver()
    diff_prob = cpt.DiffractionProblem(body=array, wave_direction=B, water_depth=depth,omega=w)
    diff_result = solver.solve(diff_prob,keep_details=(True))
    rad_prob = [
        cpt.RadiationProblem(body=array, radiating_dof=dof, water_depth=depth,omega=w)
        for dof in array.dofs
        ]
    rad_result = solver.solve_all(rad_prob,keep_details=(True))
    dataset = cpt.assemble_dataset(rad_result + [diff_result])

    RAO_vals, CWR = PTO.RAO(diff_prob,diff_result,dataset,array,w,char_dim,point_absorber,controls)
    print('RAO',RAO_vals)

    return diff_result,rad_result,RAO_vals,lam,CWR

def elevation(res,lam,diff_result,rad_result,RAO_vals,controls,N,rel_dim):
    import numpy as np
    from capytaine.bem.airy_waves import airy_waves_free_surface_elevation
    import capytaine as cpt
    import matplotlib.pyplot as plt

    solver = cpt.BEMSolver()

    # defining the computational grid and preparing post-process data
    x1, x2, y1, y2 = -(lam + rel_dim) + 300, (lam + rel_dim + 40 + 300), -25, 100
    ny = int(res*(abs(y1)+y2))
    nx = int(res*(abs(x1)+x2) + 1)
    grid = np.meshgrid(np.linspace(x1, x2, nx), np.linspace(y1, y2, ny))
    diffraction = solver.compute_free_surface_elevation(grid, diff_result)  # wave el due to diffraction
    print('diffracted waves computed')

    # this loops handles the radiated wave field
    multiplications = []
    for i in range(3):
        mult_result = solver.compute_free_surface_elevation(grid, rad_result[i]) * RAO_vals[i]
        multiplications.append(mult_result)

    radiation = sum(multiplications)
    print('radiated waves computed')

    incoming_fse = airy_waves_free_surface_elevation(grid, diff_result)     # incident wave el
    print('incident waves computed')

    total = diffraction + incoming_fse + radiation                          # total wave el

    #### here, you can plot the wave field if you would like. This is where ###
    #### I generate my wave field plots for the paper #########################
    
    import matplotlib.patheffects as path_effects
    # plots
    Z = np.abs(total)
    X = grid[0]
    Y = grid[1]
    pcm = plt.pcolormesh(X, Y, Z)
    plt.xlabel("x")
    plt.ylabel("y")
    colorbar = plt.colorbar()
    colorbar.set_label(r"Total Wave Elevation, $\eta$")
    plt.tight_layout()
    print('tip')
    plt.savefig('test_field.pdf')
    print('top')
    plt.clf()

    return total, incoming_fse, x1, x2, nx, y1, y2, ny






        # pcm.set_clim([-2, 2])
    # # Add markers with black outline
    # plt.scatter(xtrans, ytrans, marker='_', color='red', s=200, edgecolor='black', linewidth=3)
    # # Add arrow with black outline
    # plt.arrow(-100, 50, 50, 0, color='black', width=0.3, head_width=7, head_length=7)
    # plt.arrow(-100, 50, 50, 0, color='red', width=0.2, head_width=5, head_length=5)

    # Add text with black outline
    #text = plt.text(-75, 75, 'Incident Waves', color='red', fontsize=12, ha='center', va='center')
    #text.set_path_effects([path_effects.Stroke(linewidth=3, foreground='black'), path_effects.Normal()])