'''this file solves the hydrodynamics in hydro() and the wave elevation
in elevation(). hydro() will also use Capytaine's built in RAO solver if
controls=False. elevation() will compute the elevation due to incident 
waves, diffracted waves, and radiated waves, as well as multiply the
radiated waves generated by each body by the body's RAO and sum the 
radiated wave fields of every body before adding them to the incident
and diffracted. The math is detailed in the paper.'''

'''LAST UPDATE" OCT 16TH 2025'''

def hydro(array,B,depth,w,char_dim,controls,point_absorber):
    import capytaine as cpt
    import numpy as np
    import PTO

    g = 9.81                # gravitational constant (m/s^2)
    k = w**2/g              # wave number infinite depth (rad^2/m)
    lam = int(2*np.pi/k)    # wavelength infinite depth (m)
    
    # solving hydrodynamics using Capytaine solver
    solver = cpt.BEMSolver()
    diff_prob = cpt.DiffractionProblem(body=array, wave_direction=B, water_depth=depth,omega=w)
    diff_result = solver.solve(diff_prob,keep_details=(True))
    rad_prob = [
        cpt.RadiationProblem(body=array, radiating_dof=dof, water_depth=depth,omega=w)
        for dof in array.dofs
        ]

    rad_result = solver.solve_all(rad_prob,keep_details=(True))
    dataset = cpt.assemble_dataset(rad_result + [diff_result])

    RAO_vals, CWR = PTO.RAO(diff_prob,diff_result,dataset,array,w,char_dim,point_absorber,controls)

    return diff_result,rad_result,RAO_vals,lam,CWR

def elevation(res,lam,diff_result,rad_result,RAO_vals,controls,rel_dim):
    import numpy as np
    from capytaine.bem.airy_waves import airy_waves_free_surface_elevation
    import capytaine as cpt
    import matplotlib.pyplot as plt
    from scipy.interpolate import griddata

    solver = cpt.BEMSolver()

    # defining the computational grid and preparing post-process data
    x1, x2, y1, y2 = -20, 20, -20, 20
    ny = int(res*(abs(y1)+y2))
    nx = int(res*(abs(x1)+x2) + 1)
    grid = np.meshgrid(np.linspace(x1, x2, nx), np.linspace(y1, y2, ny))
    diffraction = solver.compute_free_surface_elevation(grid, diff_result)  # wave el due to diffraction
    radiation = solver.compute_free_surface_elevation(grid, rad_result[0]) * RAO_vals
    incoming_fse = airy_waves_free_surface_elevation(grid, diff_result)     # incident wave el
    total = diffraction + incoming_fse + radiation                          # total wave el

    X = grid[0]
    Y = grid[1]
    points = np.column_stack((-10, 0))
    elevation_of_interest = griddata((X.ravel(), Y.ravel()), total.ravel(), points, method='linear')

    return total, incoming_fse, x1, x2, nx, y1, y2, ny, elevation_of_interest





